/**
 * Puts SVG filter definitions into a page so CSS and canvas `filter` values of
 * the form `url(#id)` can find them.
 *
 * One hidden <svg> holds them all and is rewritten whole when the set changes.
 * The markup is generated by `planFilters` from numbers and a validated colour
 * and ids with unsafe characters removed, never from free text.
 */

const DEFAULT_HOLDER = 'cb-filter-defs'

/**
 * @param holderId  Which holder to write. Each place that shows sources has its
 *                  own, so one closing does not take the filters from another.
 */
export function setFilterDefs(doc: Document, markup: string, holderId: string = DEFAULT_HOLDER): void {
  let holder: Element | null = doc.getElementById(holderId)
  if (!holder) {
    holder = doc.createElementNS('http://www.w3.org/2000/svg', 'svg')
    holder.setAttribute('id', holderId)
    holder.setAttribute('width', '0')
    holder.setAttribute('height', '0')
    holder.setAttribute('aria-hidden', 'true')
    holder.setAttribute('style', 'position:absolute;width:0;height:0;overflow:hidden;pointer-events:none')
    doc.body.appendChild(holder)
  }
  holder.innerHTML = `<defs>${markup}</defs>`
}

/** Removes a holder and the filters in it. */
export function clearFilterDefs(doc: Document, holderId: string = DEFAULT_HOLDER): void {
  doc.getElementById(holderId)?.remove()
}
