import type { SnapshotFilter } from '../../../shared/host'

/**
 * Turns a source's filters into what draws them.
 *
 * The preview (a video element styled with CSS) and the recorder (a canvas with
 * `ctx.filter`) both understand CSS filter functions and `url(#id)` references
 * to SVG filters, so one plan serves both and they cannot drift apart. The
 * simple adjustments are plain CSS functions; sharpen and chroma key are SVG
 * filters, defined once here. Cropping is geometry, not a filter, and is handed
 * back separately.
 */

export interface Crop { left: number; right: number; top: number; bottom: number }

export interface FilterPlan {
  /** A value for CSS `filter` / canvas `ctx.filter`; 'none' when nothing applies. */
  css: string
  /** SVG `<filter>` elements the css refers to, or '' if it refers to none. */
  defs: string
  crop: Crop
}

export const NO_CROP: Crop = { left: 0, right: 0, top: 0, bottom: 0 }

const num = (v: unknown, fallback: number) => (typeof v === 'number' && Number.isFinite(v) ? v : fallback)
const clamp = (v: number, lo: number, hi: number) => Math.min(hi, Math.max(lo, v))

/** The id an SVG filter is given. Ids are generated by the app, but only safe characters are kept. */
export const filterDomId = (id: string) => `cbf-${id.replace(/[^A-Za-z0-9_-]/g, '')}`

export function hexToRgb(hex: string): [number, number, number] {
  const m = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(hex)
  if (!m) return [0, 1, 0]
  const h = m[1].length === 3 ? m[1].split('').map((c) => c + c).join('') : m[1]
  return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16) / 255) as [number, number, number]
}

const fixed = (n: number) => Number(n.toFixed(4))

/** A convolution that sharpens by `strength` (0 leaves the picture alone). */
function sharpenDef(id: string, strength: number): string {
  const a = fixed(clamp(strength, 0, 2))
  const kernel = [0, -a, 0, -a, fixed(1 + 4 * a), -a, 0, -a, 0].join(' ')
  return `<filter id="${filterDomId(id)}" x="0" y="0" width="100%" height="100%" color-interpolation-filters="sRGB">` +
    `<feConvolveMatrix order="3" kernelMatrix="${kernel}" preserveAlpha="true" edgeMode="duplicate"/></filter>`
}

/**
 * Makes pixels near the key color transparent.
 *
 * Distance from the key is worked out with matrix and table primitives (there is
 * no absolute-value primitive): each channel's difference is moved to 0..1 around
 * a midpoint, folded with a V-shaped table, summed into the alpha channel and
 * ramped between "similar" and "similar + smooth". That alpha then masks the
 * untouched picture.
 */
function chromaKeyDef(id: string, keyColor: string, similarity: number, smoothness: number): string {
  const [kr, kg, kb] = hexToRgb(keyColor)
  const edge = clamp(similarity, 1, 1000) / 1000 * 4
  const width = Math.max(0.02, clamp(smoothness, 1, 1000) / 1000 * 4)
  const half = (k: number) => fixed(0.5 - 0.5 * k)

  const toDifference = [
    `0.5 0 0 0 ${half(kr)}`,
    `0 0.5 0 0 ${half(kg)}`,
    `0 0 0.5 0 ${half(kb)}`,
    '0 0 0 0 1',
  ].join(' ')

  const gain = fixed(1 / width)
  const toAlpha = [
    '0 0 0 0 0', '0 0 0 0 0', '0 0 0 0 0',
    `${gain} ${gain} ${gain} 0 ${fixed(-edge / width)}`,
  ].join(' ')

  const dom = filterDomId(id)
  return `<filter id="${dom}" x="0" y="0" width="100%" height="100%" color-interpolation-filters="sRGB">` +
    `<feColorMatrix in="SourceGraphic" type="matrix" values="${toDifference}" result="difference"/>` +
    `<feComponentTransfer in="difference" result="folded">` +
    `<feFuncR type="table" tableValues="1 0 1"/><feFuncG type="table" tableValues="1 0 1"/><feFuncB type="table" tableValues="1 0 1"/>` +
    `</feComponentTransfer>` +
    `<feColorMatrix in="folded" type="matrix" values="${toAlpha}" result="mask"/>` +
    `<feComposite in="SourceGraphic" in2="mask" operator="in"/></filter>`
}

/**
 * @param scale   how much the picture is drawn larger or smaller than its own
 *                pixels; blur is given in pixels of the finished picture, so it
 *                follows.
 */
export function planFilters(filters: readonly SnapshotFilter[], scale = 1): FilterPlan {
  const css: string[] = []
  const defs: string[] = []
  let crop: Crop = { ...NO_CROP }

  for (const f of filters) {
    switch (f.type) {
      case 'color-correction': {
        const brightness = clamp(1 + num(f.brightness, 0), 0, 3)
        const contrast = clamp(num(f.contrast, 1), 0, 4)
        const saturation = clamp(num(f.saturation, 1), 0, 4)
        const hue = clamp(num(f.hue, 0), -180, 180)
        const opacity = clamp(num(f.opacity, 1), 0, 1)
        if (brightness !== 1) css.push(`brightness(${fixed(brightness)})`)
        if (contrast !== 1) css.push(`contrast(${fixed(contrast)})`)
        if (saturation !== 1) css.push(`saturate(${fixed(saturation)})`)
        if (hue !== 0) css.push(`hue-rotate(${fixed(hue)}deg)`)
        if (opacity !== 1) css.push(`opacity(${fixed(opacity)})`)
        break
      }
      case 'blur': {
        const radius = clamp(num(f.radius, 0), 0, 40) * scale
        if (radius > 0) css.push(`blur(${fixed(radius)}px)`)
        break
      }
      case 'sharpen': {
        if (clamp(num(f.strength, 0), 0, 2) > 0) {
          defs.push(sharpenDef(f.id, f.strength))
          css.push(`url(#${filterDomId(f.id)})`)
        }
        break
      }
      case 'chroma-key': {
        defs.push(chromaKeyDef(f.id, f.keyColor, num(f.similarity, 80), num(f.smoothness, 50)))
        css.push(`url(#${filterDomId(f.id)})`)
        const opacity = clamp(num(f.opacity, 1), 0, 1)
        if (opacity !== 1) css.push(`opacity(${fixed(opacity)})`)
        break
      }
      case 'crop': {
        // Several crops add up.
        const side = (v: unknown) => Math.max(0, Math.round(num(v, 0)))
        crop = {
          left: crop.left + side(f.left), right: crop.right + side(f.right),
          top: crop.top + side(f.top), bottom: crop.bottom + side(f.bottom),
        }
        break
      }
    }
  }

  return { css: css.length ? css.join(' ') : 'none', defs: defs.join(''), crop }
}

/**
 * The part of a picture that is left after cropping, in its own pixels, or null
 * if the crop would leave nothing (in which case the picture is drawn uncropped
 * rather than not at all).
 */
export function croppedArea(width: number, height: number, crop: Crop): { sx: number; sy: number; sw: number; sh: number } | null {
  const sw = width - crop.left - crop.right
  const sh = height - crop.top - crop.bottom
  if (!(sw >= 1) || !(sh >= 1)) return null
  return { sx: crop.left, sy: crop.top, sw, sh }
}

export const hasCrop = (c: Crop) => c.left > 0 || c.right > 0 || c.top > 0 || c.bottom > 0

/**
 * The crop as a CSS `object-view-box`, for showing a cropped picture in an
 * element. Percentages, because the box is resolved against the picture's own
 * size, which the page only learns when the picture loads.
 */
export function cropViewBox(crop: Crop, width: number, height: number): string | undefined {
  if (!hasCrop(crop) || !(width > 0) || !(height > 0)) return undefined
  const area = croppedArea(width, height, crop)
  if (!area) return undefined // nothing would be left, so show it all

  const pct = (v: number, of: number) => `${fixed((v / of) * 100)}%`
  return `inset(${pct(crop.top, height)} ${pct(crop.right, width)} ${pct(crop.bottom, height)} ${pct(crop.left, width)})`
}
